### ISSUE TITLE
UX QA 1.1 - Home

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#48]
HEADER
- [x] .main-header-item - Font-face: Mallory medium / letter-spacing: 2px;
- [x] header height: 80px
- [x] Navbar link text colors (all including Login): #789BB6 
- [x] Link active state: make text color #FFFFFF and Mallory Bold, remove padding background color
- [x] Login: OffState - display only "LOGIN" in Mallory medium and same size as other navbar links and letter spacing, #789BB6
- [x] Login: OnState  - show 4 icons (in assets folder). See comp attached. 
![web 1280 home - login view](https://cloud.githubusercontent.com/assets/25487/19983187/5910a7ee-a1df-11e6-9795-dd7cf185dd01.png)

**Home Page**

OVERLAY CONTAINER

- [x] .home-page .hero-overlay-title -  Font-face: YaleNew Roman. line-height: 1.25em;
- [x] .hero-overlay-text - Font-face: Mallory Book. font-size: .75 em; line-height: 1.25em;
- [x] Welcome text copy: Transcribe over 90 years of drama programs in the Yale University Library. Let's get started:
- [x] .home-page .hero-overlay-container: bg-color: #1A1A1A at 80%
- [x] Button text: Font-face: Mallory bold
- [x] Button color: #69A7C7

SPLASH IMAGE CAROUSEL:
- [x] Can we rotate a selection of 4 images here?

ERA OVERVIEW

- [x] BG Color (.panoptes-main): #1A1A1A
- [x] .drama-era-image-container: width: 540px height: 270px
- [x] .drama-era-image-container .drama-era-image-overlay / background: rgba(0, 0, 0, 0.75) / height: 50 px
- [x] .drama-era-image-overlay   font-face: YaleNew Roman (small caps characters) /  color: #DDDDDD

- [x] Rollover overlay color (.drama-era-image-overlay:hover): #00356B (80% transparency)
- [x] .drama-era-image-container border: #555555 1px
- [x] Increase padding above the top row of containers to 80px
- [x] Gutter width between two columns: 40 px
- [x] Gutter width between rows: 40 px

FOOTER

- [x] Use Scribe SVG graphic

**Comment by duhaime** [comment]
On the image rotation, we can do that but need to identify somewhere the list of four images for each section. These are currently identified in `project/ensemble-at-yale/subjects/groups.csv`, though we likely would want a different config file to identify the locations of each image for each section. If you can put together a roster of images per section, we could get this going quickly.
