### ISSUE TITLE
Design QA 1.4 - Final 

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#75]
- [x] .hero-overlay-button: { font-weight: 500; } 
- [x] .hero-overlay-text:  { font-size: .7em; font-family: Mallory Light}
- [x] Menu link text - when Active, use this bold font weight: 500.
- [x] LOGIN: When clicking onto the Google login, I get this message: 
![screen shot 2016-11-14 at 11 12 13 am](https://cloud.githubusercontent.com/assets/25487/20272210/3c7636e2-aa5b-11e6-80b5-1c5098ae43f2.png)

- [x] LOGIN icons: Update icons w/ .svg files in the Assets folder
- [x] LINK "DhLab" icon to dhlab.yale.edu
- [x] LINK the Yale University Library mark to library.yale.edu
- [x] MARK: .task-area.mark: { font-size: .825.em; font-family: Mallory Light}

ABOUT PAGE
- [x] Page Header: Font-family: YaleNew; Move 40 px to the right; 
- [x] Body text: Font-family: Mallory Light; Color: #333333; Size: .825em
- [x] Content Header: font-size: 1.25em; Color: #00356B
- [x] Top Image area:  560 x 300 px
- [x] Sponsor text area: 200 px height
- [x] Bottom image area: 300 px height
- [x] Left margin width: 40 px

TRANSCRIBE PAGE
- [x] .minor-button.ghost, .small-button.ghost { font-size: .9em; font-weight: 400; font-family: Mallory; letter-spacing: 0.25px; padding: .5em 1em 0.3em 1em;

COLLECTION VIEW
- [x] Page Header: Font-family: YaleNew; Move 16 px to the right; 
- [x] Content Area padding: left margin same width as the "DHLab" square area. ~72px
- [x] Body text: Font-family: Mallory Light; Color: #333333; Size: .825em
